packages:
  - apps/*
  - packages/*
  - tooling/*

catalog:
  "@tanstack/react-query": ^5.65.1
  "@tanstack/react-query-devtools": ^5.65.1
  "@trpc/client": ^11.0.0-rc.730
  "@trpc/react-query": ^11.0.0-rc.730
  "@trpc/server": ^11.0.0-rc.730
  "@types/node": ^22.12.0
  eslint: ^9.19.0
  prettier: ^3.4.2
  tailwindcss: ^3.4.14
  typescript: ^5.7.3
  zod: ^3.24.1

catalogs:
  react18:
    react: 18.3.1
    react-dom: 18.3.1
    "@types/react": ^18.3.1
    "@types/react-dom": ^18.3.1

  react19:
    react: 19.0.0
    react-dom: 19.0.0
    "@types/react": ^19.0.8
    "@types/react-dom": ^19.0.3
